textAnalyis/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('webApp/', include('webApp.urls')),
]

webApp/urls.py
from django.urls import path
from . import views

app_name = 'webApp'
urlpatterns = [
    path('sentiment_analysis/', views.sentiment_analysis, name='sentiment_analysis'),
    path('news/', views.news, name='news'),
    # other URL patterns
]

templates/contact.html
{% extends "base.html" %}
{% block content %}
{% load static %}
    <br><br><br><br><br>
    <!-- CONTACT ADDRESS AREA START -->
    <div class="ltn__contact-address-area mt-100 mb-90">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{message.tags}} show-notification" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            <strong>{{message}}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="col-lg-4">
                    <div class="ltn__contact-address-item ltn__contact-address-item-3 box-shadow">
                        <div class="ltn__contact-address-icon">
                            <img src="{% static "img/icons/10.png" %}" alt="Icon Image">
                        </div>
                        <h3>Email Address</h3>
                        <p>info@gmail.com <br>
                            abhayafyp@gmail.com</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="ltn__contact-address-item ltn__contact-address-item-3 box-shadow">
                        <div class="ltn__contact-address-icon">
                            <img src="{% static "img/icons/11.png" %}" alt="Icon Image">
                        </div>
                        <h3>Phone Number</h3>
                        <p>01-556789 <br> +987-6543210</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="ltn__contact-address-item ltn__contact-address-item-3 box-shadow">
                        <div class="ltn__contact-address-icon">
                            <img src="{% static "img/icons/12.png" %}" alt="Icon Image">
                        </div>
                        <h3> Address</h3>
                        <p>Dhapakhel <br>
                            Lalitpur , Nepal</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- CONTACT ADDRESS AREA END -->
    <hr>

    <!-- CONTACT MESSAGE AREA START -->
    <div class="ltn__contact-message-area mb-20">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ltn__form-box contact-form-box box-shadow white-bg">
                        <h4 class="title-2">Enquiry Form</h4>
                        <form id="contact-form" action="{% url 'contact' %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input-item input-item-name ltn__custom-icon">
                                     {{ form.name }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-item input-item-email ltn__custom-icon">
                                         {{ form.email }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-item input-item-phone ltn__custom-icon">
                                       {{ form.phone }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-item input-item-service ltn__custom-icon">
                                        {{ form.service }}
                                    </div>
                                </div>
                            </div>
                            <div class="input-item input-item-textarea ltn__custom-icon">
                                {{ form.message }}
                            </div>
                            <div class="btn-wrapper mt-0">
                                <button class="btn theme-btn-1 btn-effect-1 text-uppercase" type="submit">Submit</button>
                            </div>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- CONTACT MESSAGE AREA END -->
    

    <!-- GOOGLE MAP AREA START -->
    <div class="google-map">

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d28276.95334855067!2d85.30980323624851!3d27.63630907826275!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb176b47f72e53%3A0x5075fb8e3638c5d7!2sDhapakhel%2C%20Lalitpur%2044700!5e0!3m2!1sen!2snp!4v1713281300094!5m2!1sen!2snp" width="100%" height="100%" frameborder="0" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
    <!-- GOOGLE MAP AREA END -->

{% endblock content %}


templates/news.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<br><br>
<!-- BREADCRUMB AREA START -->
<div class="ltn__breadcrumb-area text-left bg-overlay-white-30 bg-image mt-100 p-5 " >
    <div class="col-lg-12">
        <div class="ltn__breadcrumb-inner">
            <h1 class="page-title">News</h1>
            <a href="{% url "index" %}"><span class="ltn__secondary-color"><i class="fas fa-home"></i></span> Home</a>
        </div>
    </div>
</div>
<!-- BREADCRUMB AREA END -->

<!-- BLOG AREA START (blog-3) -->
<div class="ltn__blog-area">
    <div class="container">
        {% if news_list %}
        <div class="row">
            <div class="col-lg-12">
                <h1 class="section-title text-center">News Feeds</h1>
            </div>
        </div>
        <div class="row ltn__blog-slider-one-active slick-arrow-1 ltn__blog-item-3-normal">
            <!-- Iterate over news items from session data -->
            
            {% for news_item in news_list %}
            <div class="col-lg-12">
                <div class="ltn__blog-item ltn__blog-item-3">
                    <div class="ltn__blog-brief">
                        <h3 class="ltn__blog-title"><a href="{{ news_item.title_link }}" style="color: red; font-weight: bold;">{{ news_item.title_text }}</a></h3>
                        <div class="ltn__blog-meta-btn">
                            <div class="ltn__blog-meta">
                                <a href="{{ news_item.title_link }}" class="text-primary" style="display: inline-block; max-width: 200px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">{{ news_item.title_link }}</a>
                            </div>
                        </div>
                        <a href="{{ news_item.title_link }}" class="btn btn-primary p-2">Read more</a>
                    </div>
                    
                </div>
            </div>
            {% endfor %}

            {% else %}
            <div class="col-lg-12">
                <h1 class="section-title text-center">No news found in the session.</h1>
            </div>

            {% endif %}
            
        </div>
    </div>
</div>
<!-- BLOG AREA END -->

{% endblock content %}

templates/sentiment_analysis_form.html

{% extends 'base.html' %}

{% block content %}
  <!-- CONTACT MESSAGE AREA START -->
  <br><br><br>
  <div class="ltn__contact-message-area mb-120">
    <div class="container">
      <div class="row mt-120">
        <div class="col-lg-12">
          <div class="ltn__form-box contact-form-box box-shadow white-bg mt-220">
            <h4 class="title-2">Try Demo</h4>
            <form method="post" action="{% url "webApp:sentiment_analysis" %}" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary rounded-pill">Submit</button>
            </form>
            {% if error_message %}
              <div class="alert alert-danger">{{ error_message }}</div>
            {% endif %}
            {% if sentiments %}
              <h4>Sentiment Analysis Results</h4>
              <ul>
                {% for sentiment in sentiments %}
                  <li>{{ sentiment.label }} ({{ sentiment.score }})</li>
                {% endfor %}
              </ul>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- CONTACT MESSAGE AREA END -->
{% endblock content %}

templates/sentiment_analysis_result.html

<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8" />
    <title> Sentiment Analysis </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="Dashboard Template" name="description" />
    <meta content="MyraStudio" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static "assets/images/favicon.ico" %}">

    <!-- App css -->
    <link href="{% static "assets/css/bootstrap.min.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "assets/css/icons.min.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "assets/css/theme.min.css" %}" rel="stylesheet" type="text/css" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <!-- Begin page -->
    <div id="layout-wrapper">
        
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">
            <div class="page-content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-8">
                            <a href="{% url 'webApp:sentiment_analysis' %}" class="btn btn-primary"><i class="fa fa-arrow-left"></i> Go Back</a>
                            <br><br>
                            <h3>Sentiment Analysis Results</h3>


                            <div class="card-body" style="max-height:600px;">
                                <h4 class="card-title">Bar Chart</h4>
                                <canvas id="sentimentChart"></canvas>
                    
                                <script>
                                    // Parse chart data JSON
                                    var chartData = JSON.parse('{{ chart_data_json|escapejs }}');
                    
                                    // Create Chart.js bar chart
                                    var ctx = document.getElementById('sentimentChart').getContext('2d');
                                    var sentimentChart = new Chart(ctx, {
                                        type: 'bar',
                                        data: {
                                            labels: chartData.labels,
                                            datasets: [{
                                                label: 'Sentiment Analysis',
                                                data: chartData.data,
                                                backgroundColor: [
                                                    'rgba(75, 192, 192, 0.2)',
                                                    'rgba(255, 99, 132, 0.2)',
                                                    'rgba(255, 206, 86, 0.2)'
                                                ],
                                                borderColor: [
                                                    'rgba(75, 192, 192, 1)',
                                                    'rgba(255, 99, 132, 1)',
                                                    'rgba(255, 206, 86, 1)'
                                                ],
                                                borderWidth: 1
                                            }]
                                        },
                                        options: {
                                            scales: {
                                                y: {
                                                    beginAtZero: true
                                                }
                                            }
                                        }
                                    });
                                </script>
                            </div> <!-- end card-body-->
                        </div> <!-- end col -->
                    
                        <div class="col-lg-4">
                            <div class="card-body" style="max-height:300px;">
                                <h4 class="card-title">Circular Chart</h4>
                                <canvas id="circularChart"></canvas>
                    
                                <script>
                                    // Parse chart data JSON
                                    var totalData = {{ chart_data_json|safe }};
                                    var total = totalData.total_data;
                    
                                    // Create Chart.js doughnut chart
                                    var ctx2 = document.getElementById('circularChart').getContext('2d');
                                    var circularChart = new Chart(ctx2, {
                                        type: 'doughnut',
                                        data: {
                                            labels: ['Total Analayzed Data :' + total],
                                            datasets: [{
                                                label: 'Total Data',
                                                data: [total],
                                                backgroundColor: [
                                                    'rgba(54, 162, 235, 0.5)',
                                                ],
                                                borderColor: [
                                                    'rgba(54, 162, 235, 1)',
                                                ],
                                                borderWidth: 1
                                            }]
                                        },
                                        options: {
                                            cutout: '75%', // Adjust the cutout size as needed
                                            responsive: true,
                                            maintainAspectRatio: false
                                        }
                                    });
                                </script>
                            </div> <!-- end card-body-->
                        </div> <!-- end col -->
                    </div>
                    <!-- end row-->
                    
                </div> <!-- container-fluid -->
            </div>
            <!-- End Page-content -->

            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            2024 © Results Dashboard.
                        </div>
                        <div class="col-sm-6">
                            <div class="text-sm-right d-none d-sm-block">
                                Design & Develop by Abhaya
                            </div>
                        </div>
                    </div>
                </div>
            </footer>

        </div>
        <!-- end main content-->

    </div>
    <!-- END layout-wrapper -->

    <!-- Overlay-->
    <div class="menu-overlay"></div>


    <!-- jQuery  -->
    <script src="{% static "assets/js/jquery.min.js" %}"></script>
    <script src="{% static "assets/js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "assets/js/metismenu.min.js" %}"></script>
    <script src="{% static "assets/js/waves.js" %}"></script>
    <script src="{% static "assets/js/simplebar.min.js" %}"></script>

    <!-- Chart Js-->
    <script src="{% static "assets/plugins/chart-js/chart.min.js" %}"></script>

    <!-- Chart Custom Js-->
    <script src="{% static "assets/pages/chartjs-demo.js" %}"></script>



    <!-- App js -->
    <script src="{% static "assets/js/theme.js" %}"></script>

</body>

</html>



templates/test.html

 <!-- CONTACT MESSAGE AREA START -->
 <div class="ltn__contact-message-area mb-120 ">
  <div class="container">
      <div class="row">
          <div class="col-lg-12">
              <div class="ltn__form-box contact-form-box box-shadow white-bg mt-120">
                  <h4 class="title-2">Try Demo</h4>
                  <div class="row">
                    <div class="col-xl-6">
                        <div class="card">
                            <div class="card-body">
                
                                <h4 class="card-title">Line Chart</h4>
                                <p class="card-subtitle mb-4">Example of line chart chart js.</p>
                                {% for err in errors %}
                                <li> {{err}}</li>
                                {% endfor %}

                                <canvas id="lineChart"></canvas>
                
                            </div> <!-- end card-body-->
                        </div> <!-- end card-->
                    </div> <!-- end col -->
              </div>
          </div>
      </div>
  </div>
</div>
<!-- CONTACT MESSAGE AREA END -->